# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "deploy"
    deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:

            # Checks-out your repository under $GITHUB_WORKSPACE
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: true  # Fetch Hugo themes
                fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

            - name: Checkout actual website build
              uses: actions/checkout@v2
              with:
                repository: 'ronangaillard/ronangaillard.github.io'
                path: 'public'

            # Sets up the latest version of Hugo
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: 'latest'

            # Builds the site using the latest version of Hugo
            # Also specifies the theme we want to use
            - name: Build
              run: hugo --theme=cactus

            # Commit build
            - name: Commit Build
              run: |
                cd public
                git config --local user.email "ronan.gaillard@live.fr"
                git config --local user.name "Ronan Gaillard"
                git commit -am "Add changes"
                git remote set-url origin https://ronangaillard:${{ secrets.MY_GITHUB_TOKEN }}@github.com/ronangaillard/ronangaillard.github.io.git
                git remote
                git push origin master